name: Deploy to GitHub Pages

on:
  push:
    branches: [v2]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Bun environment
        uses: ./.github/actions/setup-bun

      - name: Build
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  lighthouse:
    needs: deploy
    if: needs.deploy.result == 'success'
    uses: ./.github/workflows/_lighthouse.yml
    with:
      url: ${{ needs.deploy.outputs.page_url }}
      wait-seconds: 30
